"""create professional services

Revision ID: 124ff7cb8ffe
Revises: cf6c7e6a2dd5
Create Date: 2026-08-31 14:06:11.607436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124ff7cb8ffe'
down_revision: Union[str, Sequence[str], None] = 'cf6c7e6a2dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_services_professional_profile_id'), 'professional_services', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_professional_services_service_id'), 'professional_services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_services_service_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_professional_profile_id'), table_name='professional_services')
    op.drop_table('professional_services')
    # ### end Alembic commands ###
