"""add unique constraint to professional services

Revision ID: 1fab36a70779
Revises: 124ff7cb8ffe
Create Date: 2026-08-31 14:09:53.947381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fab36a70779'
down_revision: Union[str, Sequence[str], None] = '124ff7cb8ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_professional_service', 'professional_services', ['professional_profile_id', 'service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_professional_service', 'professional_services', type_='unique')
    # ### end Alembic commands ###
