"""create quotes

Revision ID: 22214c49c884
Revises: f96d4db15eba
Create Date: 2026-08-31 16:32:38.283961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22214c49c884'
down_revision: Union[str, Sequence[str], None] = 'f96d4db15eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('professional_service_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_service_id'], ['professional_services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_professional_service_id'), 'quotes', ['professional_service_id'], unique=False)
    op.create_index(op.f('ix_quotes_service_request_id'), 'quotes', ['service_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_service_request_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_professional_service_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
