"""create reviews

Revision ID: 33e249a07e8f
Revises: 60e7b214fbcc
Create Date: 2026-09-01 11:29:57.024118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e249a07e8f'
down_revision: Union[str, Sequence[str], None] = '60e7b214fbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_reviews_customer_profile_id'), 'reviews', ['customer_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_professional_profile_id'), 'reviews', ['professional_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_professional_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_profile_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
