"""create professional service areas

Revision ID: 87aa63c22904
Revises: 1fab36a70779
Create Date: 2026-08-31 15:05:17.371095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aa63c22904'
down_revision: Union[str, Sequence[str], None] = '1fab36a70779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_service_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_service_areas_postal_code'), 'professional_service_areas', ['postal_code'], unique=False)
    op.create_index(op.f('ix_professional_service_areas_professional_profile_id'), 'professional_service_areas', ['professional_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_service_areas_professional_profile_id'), table_name='professional_service_areas')
    op.drop_index(op.f('ix_professional_service_areas_postal_code'), table_name='professional_service_areas')
    op.drop_table('professional_service_areas')
    # ### end Alembic commands ###
