"""create bookings

Revision ID: f5807d33821c
Revises: 22214c49c884
Create Date: 2026-08-31 17:11:42.361486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5807d33821c'
down_revision: Union[str, Sequence[str], None] = '22214c49c884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id'),
    sa.UniqueConstraint('service_request_id')
    )
    op.create_index(op.f('ix_bookings_address_id'), 'bookings', ['address_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_profile_id'), 'bookings', ['customer_profile_id'], unique=False)
    op.create_index(op.f('ix_bookings_professional_profile_id'), 'bookings', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_professional_profile_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_profile_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_address_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
