"""create service requests

Revision ID: f96d4db15eba
Revises: 87aa63c22904
Create Date: 2026-08-31 15:32:38.458119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96d4db15eba'
down_revision: Union[str, Sequence[str], None] = '87aa63c22904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_address_id'), 'service_requests', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_requests_customer_profile_id'), 'service_requests', ['customer_profile_id'], unique=False)
    op.create_index(op.f('ix_service_requests_professional_profile_id'), 'service_requests', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_id'), 'service_requests', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_service_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_professional_profile_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_profile_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_address_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
